# Generated by Django 5.1.4 on 2025-01-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_user_type_customuser_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_passenger',
            field=models.BooleanField(default=True),
        ),
    ]
