# Generated by Django 5.1.4 on 2025-01-12 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('seat_fare', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('city', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('number', models.CharField(max_length=10, unique=True)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('duration', models.IntegerField()),
                ('base_fare', models.FloatField()),
                ('running_days', models.ManyToManyField(related_name='routes', to='dashboard.day')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_station', to='railway.station')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_station', to='railway.station')),
            ],
        ),
        migrations.CreateModel(
            name='RouteHaltSegments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_number', models.IntegerField(null=True)),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='railway.route')),
                ('current_halt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_halt', to='railway.station')),
                ('previous_halt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_halt', to='railway.station')),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.upcomingdate')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='railway.route')),
            ],
        ),
        migrations.CreateModel(
            name='TrainSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.upcomingdate')),
                ('halt_segment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='railway.routehaltsegments')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('is_booked', models.BooleanField(default=False)),
                ('seat_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='railway.seatcategory')),
                ('train_segment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='railway.trainsegment')),
            ],
        ),
        migrations.CreateModel(
            name='HaltStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField(null=True)),
                ('departure_time', models.TimeField(null=True)),
                ('order', models.IntegerField(null=True)),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='halts', to='railway.route')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='railway.station')),
            ],
            options={
                'unique_together': {('station', 'route', 'order')},
            },
        ),
    ]
