# Generated by Django 5.1.4 on 2025-01-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stations',
            new_name='Station',
        ),
    ]
