# Generated by Django 5.1.4 on 2025-01-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
