# Generated by Django 5.1.4 on 2025-01-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0002_rename_stations_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
