# Generated by Django 5.1.4 on 2025-01-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0002_train_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='seat_categories',
            field=models.ManyToManyField(related_name='routes', to='railway.seatcategory'),
        ),
    ]
