# Generated by Django 5.1.4 on 2025-01-06 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0004_seatcategory_train_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='HaltStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('halt_duration', models.DurationField()),
                ('distance', models.FloatField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railway.station')),
            ],
        ),
    ]
