# Generated by Django 5.1.4 on 2025-01-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0005_haltstation'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='halt_stations',
            field=models.ManyToManyField(to='railway.haltstation'),
        ),
    ]
