# Generated by Django 5.1.4 on 2025-01-06 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0006_route_halt_stations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='halt_stations',
        ),
        migrations.AddField(
            model_name='haltstation',
            name='route',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='railway.route'),
        ),
        migrations.AlterUniqueTogether(
            name='haltstation',
            unique_together={('station', 'route')},
        ),
    ]
