# Generated by Django 5.1.4 on 2025-01-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0007_remove_route_halt_stations_haltstation_route_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='haltstation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='route',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='haltstation',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='haltstation',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='haltstation',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='haltstation',
            name='halt_duration',
        ),
        migrations.RemoveField(
            model_name='haltstation',
            name='route',
        ),
        migrations.RemoveField(
            model_name='haltstation',
            name='station',
        ),
    ]
