# Generated by Django 5.1.4 on 2025-01-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0008_alter_haltstation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
