# Generated by Django 5.1.4 on 2025-01-07 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0009_alter_route_name_alter_route_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='station',
            name='updated_at',
        ),
    ]
