# Generated by Django 5.1.4 on 2025-01-07 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0010_remove_station_created_at_remove_station_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='haltstation',
            name='arrival_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='haltstation',
            name='departure_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='haltstation',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='haltstation',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='railway.route'),
        ),
        migrations.AddField(
            model_name='haltstation',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='railway.station'),
        ),
        migrations.AlterUniqueTogether(
            name='haltstation',
            unique_together={('station', 'route', 'order')},
        ),
    ]
